### ISSUE TITLE
Use brand identity from main site

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/finder#2]
- [x] Averta ([code](https://github.com/hackclub/site/blob/master/static.config.js#L11-L25))
- [x] Colors ([palette](https://palx.jxnblk.com/2d9ce4), [code](https://github.com/hackclub/site/blob/master/src/theme.js#L4-L25))

**Comment by ifvictr** [comment]
Closed by b37375d14d004277118ec91504a06df403d91282.
