### ISSUE TITLE
When clicking a the map icon, Google Maps doesn't fully load

### ISSUE THREAD

**Issue by zachlatta** [hackclub/finder#20]
![recorded](https://user-images.githubusercontent.com/992248/36527024-38d948e4-1765-11e8-8375-a716dbca512c.gif)

**Comment by ifvictr** [comment]
Looks like a problem with Google Maps. Maybe using the school name + address isn't the best way to get a result. I'll explore the possible solutions tonight.

**Comment by itsmingjie** [comment]
Try programmatically generate address data for each school in the database?

**Comment by ifvictr** [comment]
@mj66 As far as I know, it already does that - the address is parsed and coordinates derived from that.

**Comment by itsmingjie** [comment]
Google Maps: 
`https://www.google.com/maps.google.com/?ll=latitude,longitude`

So you should probably be using the longitude and latitude values?

**Comment by ifvictr** [comment]
Should be fixed now.

**Comment by ifvictr** [comment]
Should be fixed now. Feel free to re-open if you notice this bug again.
