### ISSUE TITLE
Automatically expand radius until results are found

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/finder#22]
Proposed by @zachlatta at the core meeting

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by ifvictr** [comment]
@zachlatta I like this idea. This feature will be added as a part of the React + DS rewrite I'm working on right now.

**Comment by zachlatta** [comment]
Ah, can't wait! Awesome to hear it'll be integrated with the DS.
