### ISSUE TITLE
Add SearchAction schema

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/finder#28]
http://schema.org/SearchAction (example 3)

**Comment by ifvictr** [comment]
@lachlanjc Did I do it right in https://github.com/hackclub/finder/commit/90a3e8d72b6cf3a7b8489bb9c0cd8618a297f6b3?

**Comment by lachlanjc** [comment]
I think so! Never used that Schema specifically before. Try Google's tool: https://search.google.com/structured-data/testing-tool/u/0/
