### ISSUE TITLE
Make it clear no results are found

### ISSUE THREAD

**Issue by maxwofford** [hackclub/finder#3]
Right now it's not clear if there was an error or there were no results when I search in a location that doesn't show any cards. It would be great if it could tell me there were no results in the area or if there was a loading issue.

![screenshot from 2017-12-14 00-45-06](https://user-images.githubusercontent.com/5891442/33983177-0dd11d4a-e068-11e7-84b0-880707e8ccad.png)

**Comment by ifvictr** [comment]
Added in 75d3b604f9f188a89eec86f26ede0d4e45067efd.
