### ISSUE TITLE
Support metric system measurements

### ISSUE THREAD

**Issue by ifvictr** [hackclub/finder#4]
Currently, distances are only shown in miles (imperial system). Most non-US countries use the metric system, so we'll need an option that'll allow users to toggle between measurement systems.

Ideas:
- Guess preferred measurement system based on location (by country)
- Add switch below search bar

**Comment by prattheev** [comment]
@ifvictr Cool. I'll make the PR soon.

**Comment by ifvictr** [comment]
@prattheev That would be awesome, thanks! :smile:

**Comment by prattheev** [comment]
@ifvictr Let me know if any changes.

**Comment by prattheev** [comment]
@ifvictr Requested changes are done

**Comment by ifvictr** [comment]
Merged in 4f2441763934ae20d2bdd7bbe60f03c39635d74a! :confetti_ball: Sorry for the delay, was doing college applications.
